[package]
name = "react-native-epub-json"
version = "0.1.0"
edition = "2024"
authors = ["gudwjd1208@koreatech.ac.kr"]
description = "Convert EPUB files to React Native component structures without WebView"
keywords = ["epub", "react-native", "converter", "ebook", "parser"]
categories = ["parsing", "text-processing"]
license = "MIT"
repository = "https://github.com/jingjing2222/epub-to-rn"
readme = "README.md"

[lib]
name = "react_native_epub_json"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rn-epub-json-cli"
path = "src/main.rs"

[dependencies]
epub = "2.1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
html2text = "0.12"
base64 = "0.22"
scraper = { version = "0.20", default-features = false }
cssparser = { version = "0.31", default-features = false }

# WASM dependencies
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }

[dependencies.serde-wasm-bindgen]
version = "0.6"

[features]
default = ["console_error_panic_hook"]

[target.wasm32-unknown-unknown.dependencies]
getrandom_v2 = { version = "0.2", features = ["js"], package = "getrandom" }
getrandom    = { version = "0.3", features = ["wasm_js"] }

